default:
  image: dart

stages:
  - analyze

jobAnalyze:
  stage: analyze
  script:
    - dart pub upgrade
    - dart run ac_code_metrics:metrics lib -r gitlab > code-quality-report.json
    - dart run ac_code_metrics:metrics lib -r html
  artifacts:
    paths:
      - metrics
    reports:
      codequality: code-quality-report.json
